# Generated by Django 4.0.6 on 2022-10-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registratiion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.IntegerField()),
                ('user_email', models.CharField(max_length=100)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_mode_of_info', models.CharField(max_length=50)),
                ('user_first_time', models.CharField(max_length=50)),
                ('user_residence', models.CharField(max_length=100)),
                ('user_arrival_day', models.CharField(max_length=50)),
            ],
        ),
    ]
