# Generated by Django 4.0.6 on 2022-10-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_alter_registratiion_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registratiion',
            new_name='Registration',
        ),
    ]
