# Generated by Django 4.0.6 on 2022-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0003_rename_registratiion_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='user_name',
            new_name='user_firstname',
        ),
        migrations.AddField(
            model_name='registration',
            name='user_lastname',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
