# Generated by Django 4.0.6 on 2022-11-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0007_registration_date_of_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='date_of_registration',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='verified',
        ),
    ]
